# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Christopher Lennan
title: Machine Learning Engineer
email: christopher.lennan@gmail.com
website: clennan.github.io

# Social links
twitter_username: chris_lennan
github_username:  clennan
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: christopher-lennan
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
   I am part of the Machine Learning Engineering team at [idealo.de](www.idealo.de) where we work on 
   machine learning projects covering computer vision, natural language processing, and prediction 
   models based on tabular data. In previous positions I applied machine learning methods to text, fMRI, 
   and financial data.

   My educational background is in statistics and I had a fairly theoretical introduction to machine 
   learning. Over the last six years I have gained practical experience by implementing multiple 
   machine learning solutions in business environments. 
   
   I am proficient in *Python*, becoming better at *Scala*, and have worked with the following 
   technologies/frameworks/providers: *Apache Airflow/Kafka/Spark*, *AWS*, *Docker*, *Jenkins*, *Kubernetes*, 
   *scikit-learn*, *SQL*, *TensorFlow*.

   The sharing and inclusive character of the ML community is a major motivation for me to work 
   in this industry and I try to contribute by open sourcing projects, giving 
   talks at conferences, hosting meetups, and teaching at a digital integration school. 



# Experience Section
experience_title: Experience

# Projects Section
projects_title: Open-source projects

# Education Section
educaton_title: Education

# More Section
more_title: Talks
more_content: | # this will include new lines to allow paragraphs
   March 2019: **Strata Data Conference**, San Francisco, *Using deep learning to automatically rank millions of hotel images*

   March 2019: **Data Festival**, Munich, *Demystifying the neural network black box: An interactive session on understanding decisions made by Convolutional Neural Networks* [[slides](https://speakerdeck.com/tanujjain/demystifying-the-neural-network-black-box)][[code](https://github.com/idealo/cnn-exposed)]

   September 2018: **PyParis**, Paris, *Using Deep Learning to rank and tag millions of hotel images* [[slides](http://pyparis.org/static/slides/Christopher+Lennan+Tanuj+Jain-475f1087.pdf)][[video](https://youtu.be/WEWl4cD-y00)]

   March 2018: **code.talks commerce**, Berlin, *How we trained a bot to understand fashion requests* [[video](https://www.youtube.com/watch?v=WnRXgcr4rH4)]

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
