project:
  type: website

website:
  title: "Christopher Lennan"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/clennan
      - icon: twitter
        href: https://twitter.com/chris_lennan
      - icon: linkedin
        href: https://linkedin.com/in/christopher-lennan/
format:
  html:
    theme: cosmo
    css: styles.css
